### PR TITLE
Model dataset readme

### PR DESCRIPTION
**Pull request by kadirnar**
Added RSNA Pneumonia

### CODE REVIEW

**Comment by mburaksayici** [comment]
@kadirnar  Why did you delete documentation in here https://github.com/gesund-ai/gesundai_workshop/tree/main/Dataset ? What you can do is to put the table over the documentation.

**Comment by kadirnar** [comment]
@mburaksayici,

I edited the readme 8 days ago. but Akson developed using main branch 7 days ago. How do you want me to fix it?

**Comment by mburaksayici** [comment]
> 

@kadirnar  Can you rebase and push again? In commandline:

 git checkout model_dataset_readme 
 git rebase dev 
 solve if conflicts happens, just keep your and Aksons changes both. 
 git push origin model_dataset_readme

**Comment by mburaksayici** [comment]
> > 
> 
> @kadirnar Can you rebase and push again? In commandline:
> 
> git checkout model_dataset_readme git rebase dev solve if conflicts happens, just keep your and Aksons changes both. git push origin model_dataset_readme

@kadirnar  and git checkout dev ; git pull origin dev before doing the commands i have given

**Comment by mburaksayici** [comment]
@kadirnar also add VGG16 model that i ve sent you on keras

**Comment by vkocaman** [comment]
@kadirnar @mburaksayici is this a stale PR ?  I see conflicts.. please fix and re-PR

**Comment by mburaksayici** [comment]
> @kadirnar @mburaksayici is this a stale PR ? I see conflicts.. please fix and re-PR
still fixing. will pr today

**Comment by vkocaman** [comment]
@mburaksayici we updated this page with @Xnsam . So your edits should be based on his latest work

**Comment by vkocaman** [comment]
@kadirnar no matter you add, I'll not merge this unless you base all these fixes on Akson's latest merge

**Comment by mburaksayici** [comment]
@vkocaman  I ll rebase/fix all.

**Comment by mburaksayici** [comment]
Hi @vkocaman;

- Rebased. 
- I need to find a way to make links downloadable, and restricted to multiple clicks for batch download.
- Tutorials on model upload is lil bit outdated. 
- Done for now, Will create new branch after merge, this branch is too stale otherwise.

**Pull request merged**
